spring:
  application:
    name: Omni-BE-File

  cloud:
    gcp:
      storage:
        bucket: ${GCP_STORAGE_BUCKET}

springdoc:
  api-docs:
    path: ${FILE_SWAGGER_PATH}
  swagger-ui:
    path: ${FILE_SWAGGER_PATH}

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, metrics
  endpoint:
    health:
      show-details: never
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles:
        http.server.requests: 0.5, 0.95, 0.99
      percentiles-histogram:
        http.server.requests: true